### ISSUE TITLE
Currently the theme is changing according to the LightPrimary,LightSecondary,DarkPrimary,DarkSecondary . It should be fixed according to thhat right?

### ISSUE THREAD

**Issue by bathini79** [firecamp-dev/firecamp#60] opened 2023-08-25 05:13 UTC
Currently the theme is changing according to the LightPrimary,LightSecondary,DarkPrimary,DarkSecondary , Not Only Dark Mode And Light Mode. It should be fixed according to that right?

**Comment by Nishchit14** [comment] 2023-08-25 05:23
Thank you for your first. issue @bathini79.

Can you please explain the issue with more clarity? What exactly you're facing the problem with theming options?

**Comment by bathini79** [comment] 2023-08-25 05:28
Okay The issue is theme is not being stored in the localStorage properly . Its only storing light and dark in localStorage,which is also not working upon every refresh it'll set to default . 
A. Theme should be stored localStorage 
B. It is supposed to LightPrimary,LightSecondary,DarkPrimary,DarkSecondar.

**Comment by Nishchit14** [comment] 2023-08-25 08:53
duplicate of #45

**Comment by bathini79** [comment] 2023-08-25 10:04
I believe it is extention of that issue. That issue speaks more about blank and white theme . 
Even if we fix that , there's gonna be other problem the theme will not no which color scheme was applied . Then we have to re write the whole code logic . 
Instead we could tackle the problem together in one go

**Comment by bathini79** [comment] 2023-08-26 12:57
I'll be doing it

**Comment by bathini79** [comment] 2023-08-29 20:08
https://github.com/firecamp-dev/firecamp/pull/72

**Closed** 2023-09-04 04:48 UTC
Labels: good first issue, help wanted
